- name: Deploy to EKS with Helm
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          helm upgrade --install epick-book ./epick-book-chart \
          --set image.repository=$ECR_REGISTRY/${{ secrets.ECR_REPOSITORY }} \
          --set image.tag=${{ github.sha }}

      - name: Verify Deployment
        run: |
          kubectl rollout status deployment/epick-book-epick-book